disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "A collection of my projects"
author = { headline = "Robotics / Healthcare / Automation", name = "Bryce Hackel", image = "Profile Picture 3.png", links = [ { github = "https://github.com/bhackel" }, { linkedin = "https://linkedin.com/in/bryce-hackel" }, { youtube = "https://www.youtube.com/@bhackel" } ] }
